[languages.rs]
verification_file_suffix = '_test.rs'
compile = 'cargo build --release --workspace'
execute = '.verify-helper/runner {path}'
list_dependencies = '.verify-helper/dependency-extractor {path}'
