name: Verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: false

      - name: Cache cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install oj-verify
        run: pip3 install -U git+https://github.com/online-judge-tools/verification-helper@master

      - name: Cache verification i/o
        uses: actions/cache@v2
        with:
          path: .verify-helper/cache
          key: ${{ runner.os }}-oj-verify-${{ hashFiles('verify/**/**.rs') }}

      - name: Run oj-verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        run: oj-verify --config-file .verify-helper/config.toml run -j 2
